apiVersion: v2
name: dojo
description: A Helm chart for Dojo application
type: application
version: 1.0.1
appVersion: "0.1.0"
dependencies:
  - name: common
    version: 2.40.0
    repository: oci://registry-1.docker.io/bitnamicharts
